# Generated by Django 4.0.2 on 2022-03-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_alter_faculty_name_alter_profile_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', to='main.Tag'),
        ),
    ]
