# Generated by Django 4.0.2 on 2022-03-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_vk_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vk_url',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Ссылка ВК'),
        ),
    ]
