# Generated by Django 4.0.2 on 2022-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('main', '0007_alter_profile_vk_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='room.Room'),
        ),
    ]
