# Generated by Django 4.0.2 on 2022-04-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('main', '0008_profile_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rooms',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile', to='room.Room'),
        ),
    ]
